# mk (c) 2019
---
- name: Get VPC facts
  ec2_vpc_net_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"

    aws_region: "{{ aws_region }}"   
    filters:
       "tag:Name": "{{ prefix }}*"
  register: vpc_facts
- set_fact:
    vpc_id: "{{ vpc_facts.vpcs.0.vpc_id }}"

- name: Get subnet facts
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"

    aws_region: "{{ aws_region }}"   
    filters:
       vpc-id: "{{ vpc_id }}"
       "tag:Name": "{{ prefix }}*"
  register: subnet_facts
- set_fact:
    subnet_id: "{{ subnet_facts.subnets.0.subnet_id }}"

- ec2_group_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
       
    filters:
      vpc-id: "{{ vpc_id }}"
      group-name: "{{ prefix }}*"
  register: sg_facts
- set_fact:
    sec_group_id: "{{ sg_facts.security_groups.0.group_id }}"
    sec_group_name: "{{ sg_facts.security_groups.0.group_name }}"
