# mk (c) 2019
---
- name: Get the master host public IP
  local_action:
    module: uri
    url: "{{ public_ip_url }}"
    return_content: yes
  register: ip_lookup
- set_fact:
    master_ip: "{{ ip_lookup.content | regex_replace('\n','') }}"

- name: Get filtered AMI ID
  ec2_ami_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"

    aws_region: "{{ aws_region }}"   
    owners: ["amazon"]
    filters:
      name: "{{ ec2_ami_name_filter }}"
      virtualization-type: "hvm"
      root-device-type: "ebs"
  register: ami_facts
- set_fact:
    ami_id: "{{ ami_facts.images[-1].image_id }}" 
    ami_snap_id: "{{ ami_facts.images[-1].block_device_mappings.0.ebs.snapshot_id }}"
